services:
  postgres:
    image: postgres:18-alpine
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbitmq", "5672" ]
      interval: 5s
      timeout: 5s
      retries: 5

  userservice:
    build: ./userservice
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      authservice:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - AUTH_HOST=authservice
      - SPRING.RABBITMQ.HOST=rabbitmq
      - BFF_HOST=bff
  messageservice:
    build: ./messageservice
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      authservice:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - AUTH_HOST=authservice
      - SPRING.RABBITMQ.HOST=rabbitmq
      - GRPC_HOST=userservice

  authservice:
    build: ./authservice
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AUTH_PUB_HOST=authservice
      - USER_HOST=userservice
      - BFF_HOST=bff
    healthcheck:
      test: [ "CMD", "nc", "-z", "authservice", "9000" ]
      interval: 5s
      timeout: 5s
      retries: 5

  bff:
    build: ./bff
    ports:
      - "8080:8080"
    depends_on:
      authservice:
        condition: service_healthy
    environment:
      - AUTH_HOST=authservice
      - USER_HOST=userservice
      - MESSAGE_HOST=messageservice

volumes:
  postgres_data:
