services:
  postgres:
    image: postgres:18-alpine
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  userservice:
    build: ./userservice
    ports:
      - "8081:8081"
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      authservice:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - AUTH_HOST=authservice
      - SPRING.RABBITMQ.HOST=rabbitmq

  messageservice:
    build: ./messageservice
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      authservice:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - AUTH_HOST=authservice
      - RABBITMQ_HOST=rabbitmq
      - USER_SERVICE_GRPC_HOST=userservice
      - USER_SERVICE_GRPC_PORT=9090

  botservice:
    build: ./botservice
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy
      messageservice:
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MESSAGE_SERVICE_URL=http://messageservice:8082

      - AI_API_BASE_URL=${AI_API_BASE_URL:-http://host.docker.internal:1234/v1}
      - AI_API_MODEL_NAME=${AI_API_MODEL_NAME:-meta-llama-3.1-8b-instruct}
      - AI_API_KEY=${AI_API_KEY:-no-key-needed}
    extra_hosts:
      - "host.docker.internal:host-gateway"


  authservice:
    build: ./authservice
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AUTH_PUB_HOST=authservice
      - USER_HOST=userservice
    healthcheck:
      test: [ "CMD", "nc", "-z", "authservice", "9000" ]
      interval: 5s
      timeout: 5s
      retries: 5

  bff:
    build: ./bff
    ports:
      - "8080:8080"
    depends_on:
      authservice:
        condition: service_healthy
    environment:
      - AUTH_HOST=authservice
      - USER_HOST=userservice

volumes:
  postgres_data:
