services:
  postgres:
    image: postgres:18-alpine
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  userservice:
    build: ./userservice
    ports:
    - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  messageservice:
    build: ./messageservice
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
