spring.application.name=service3
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${AUTH_HOST:127.0.0.1}:9000
server.port=8083

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

message.service.url=${MESSAGE_SERVICE_URL:http://localhost:8082}

# AI CONFIG (LM STUDIO / OPENROUTER)
ai.api.base-url=${AI_API_BASE_URL:http://127.0.0.1:1234/v1/chat/completions}
ai.api.model-name=${AI_API_MODEL_NAME:meta-llama-3.1-8b-instruct}
ai.api.key=${AI_API_KEY:no-key-needed}