spring.application.name=authservice
server.port=9000


spring.security.oauth2.client.gateway.secret=secret
spring.security.oauth2.client.gateway.redirect-uri=http://localhost:8080/login/oauth2/code/authservice
spring.security.oauth2.client.gateway.post-logout-redirect-uri=http://localhost:8080/

spring.security.oauth2.authorizationserver.issuer=http://${AUTH_PUB_HOST:127.0.0.1}:9000

#sätta ip här verkar inte göra något
#server.address=127.0.0.1
logging.level.org.springframework.security=trace
#internal api calls
user.service.address=http://${USER_HOST:localhost}:8081/api/users
