spring.application.name=bff
server.port=8080
# internal requests, get jwt token
spring.security.oauth2.client.provider.authservice.issuer-uri=http://${AUTH_HOST:127.0.0.1}:9000

# external requests
spring.security.oauth2.client.provider.authservice.authorization-uri=http://localhost:9000/oauth2/authorize
spring.security.oauth2.client.provider.authservice.token-uri=http://${AUTH_HOST:127.0.0.1}:9000/oauth2/token
spring.security.oauth2.client.provider.authservice.jwk-set-uri=http://${AUTH_HOST:127.0.0.1}:9000/oauth2/jwks


spring.security.oauth2.client.registration.authservice.client-id=gateway-client
spring.security.oauth2.client.registration.authservice.client-secret=secret
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.authservice.redirect-uri=http://localhost:8080/login/oauth2/code/authservice
spring.security.oauth2.client.registration.authservice.scope=user.read,openid
logging.level.org.springframework.security=debug
logging.level.org.springframework.cloud.gateway=TRACE
